var uname= 'Tushar Super';
var ushop= 'Vio Smart Products';
var uwano= '917218824193';
var umail= 'liam.zinc@gmail.com';
var usubscription= 'Last Paid : 30/04/2018';
var ustatus= 'Connection Active.';
var uvideo = '<p>How to jump 4X growth?</p>';
var biturl = 'http://airx.netlify.com/v/i';
var apptitle = 'Tushar\'s Shsop'
